### ISSUE TITLE
Sandbox examples not working

### ISSUE THREAD

**Issue by cmacdonnacha** [tannerlinsley/react-charts#221]
Hey, the [Sandbox examples](https://react-charts.tanstack.com/examples/line) are not working.

**Comment by tannerlinsley** [comment]
They should be working now

**Comment by cmacdonnacha** [comment]
Still getting 404 not found: https://react-charts.tanstack.com/examples/line
